server:
  port: 8761 # 服务端口
spring:
  application:
    name: epeius-register # 服务名称
  security: # 安全配置
    user:
      name: admin # 用户名
      password: admin #密码

#-------- 服务注册中心配置 -------#
eureka:
  environment: ${spring.profiles.active}
  server:
    enable-self-preservation: true # 是否开启自我保护模式
    eviction-interval-timer-in-ms: 4000 # 清理无效节点时间 毫秒
  instance:
    hostname: ${spring.cloud.client.ip-address} # 服务注册中心实例的主机名
    prefer-ip-address: true #显示服务ip地址
  client:
    register-with-eureka: false # 是否向服务注册自己
    fetch-registry: false # 配置此客户端不获取eureka服务器注册表上的注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 指定服务注册中心的位置