swagger:
  show: true    # 是否展示UI界面
  scan-package: com.xxxx.epeius# 扫描的包地址
  info:
    title: 接口文档 # API 文档标题
    contact: # 联系信息
      name: arrows # 名字
      url: http://www.github.com # 主页地址
      email: shangmlee@foxmail.com # 邮箱

